// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Author struct {
	AuthorID        int64
	NickName        string
	Email           string
	PasswordHash    string
	Payments        string
	Bio             string
	Link            string
	ProfileImageUrl string
	AdditionalInfo  string
	CreatedAt       pgtype.Timestamptz
	LastLogin       pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
}

type Comment struct {
	Commentator   string
	PostType      string
	CommentatorID int64
	PostID        int64
	Comment       string
	CommentDate   pgtype.Timestamptz
}

type OrgSupporter struct {
	EntityType     string
	EntityID       int64
	OrgID          int64
	DonationAmount pgtype.Numeric
	DonationDate   pgtype.Timestamptz
}

type Organization struct {
	OrgID          int32
	AuthorID       int64
	Category       string
	Name           string
	Description    string
	Website        string
	ContactEmail   string
	LogoUrl        string
	AdditionalInfo string
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
}

type Project struct {
	ProjectID   int32
	AuthorID    int64
	Title       string
	Category    string
	Description string
	Link        string
	Details     string
	Payments    string
	Status      bool
	FundingGoal pgtype.Numeric
	FundsRaised pgtype.Numeric
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
}

type ProjectSupporter struct {
	EntityType     string
	EntityID       int64
	ProjectID      int64
	DonationAmount pgtype.Numeric
	DonationDate   pgtype.Timestamptz
}

type TransactionsCard struct {
	ID              int32
	UserID          pgtype.Int8
	AuthorID        pgtype.Int8
	SenderAddr      string
	ReceiverAddr    string
	ProjectID       pgtype.Int8
	Amount          pgtype.Numeric
	TransactionDate pgtype.Timestamptz
	PaymentMethod   pgtype.Text
}

type TransactionsCrypto struct {
	ID              int32
	UserID          pgtype.Int8
	AuthorID        pgtype.Int8
	SenderAddr      string
	ReceiverAddr    string
	Network         string
	Tax             pgtype.Numeric
	ProjectID       pgtype.Int8
	Amount          pgtype.Numeric
	TransactionDate pgtype.Timestamptz
	PaymentMethod   pgtype.Text
}

type User struct {
	UserID          int64
	Username        string
	Email           string
	PasswordHash    string
	ProfileImageUrl string
	CreatedAt       pgtype.Timestamptz
	LastLogin       pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
}
