// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Author struct {
	ID              int32
	NickName        string
	Email           string
	PasswordHash    string
	Payments        string
	Projects        []string
	Bio             string
	Link            string
	ProfileImageUrl string
	AdditionalInfo  []string
	CreatedAt       pgtype.Timestamptz
	LastLogin       pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
}

type Comment struct {
	ID        int32
	UserID    pgtype.Int8
	AuthorID  pgtype.Int8
	PostID    int64
	CreatedAt pgtype.Timestamp
	Message   string
}

type Organization struct {
	ID             int32
	Category       string
	Name           string
	Description    string
	Website        string
	ContactEmail   string
	LogoUrl        string
	AdditionalInfo []string
	Supporters     []int64
	CreatedAt      pgtype.Timestamp
	UpdatedAt      pgtype.Timestamp
}

type Project struct {
	ID          int32
	AuthorID    int32
	Title       string
	Category    string
	Description string
	Link        string
	Details     []string
	Payments    string
	Status      string
	Supporters  []int64
	FundingGoal pgtype.Float8
	FundsRaised pgtype.Float8
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
}

type TransactionsCard struct {
	ID              int32
	UserID          pgtype.Int8
	AuthorID        pgtype.Int8
	SenderAddr      string
	ReceiverAddr    string
	ProjectID       pgtype.Int4
	Amount          pgtype.Numeric
	TransactionDate pgtype.Timestamp
	PaymentMethod   pgtype.Text
}

type TransactionsCrypto struct {
	ID              int32
	UserID          pgtype.Int8
	AuthorID        pgtype.Int8
	SenderAddr      string
	ReceiverAddr    string
	Network         string
	Tax             pgtype.Numeric
	ProjectID       pgtype.Int4
	Amount          pgtype.Numeric
	TransactionDate pgtype.Timestamp
	PaymentMethod   pgtype.Text
}

type User struct {
	ID                     int32
	Username               string
	Email                  string
	PasswordHash           string
	DonationSum            float64
	SupportedProjects      []int64
	SupportedOrganizations []int64
	ProfileImageUrl        string
	CreatedAt              pgtype.Timestamptz
	LastLogin              pgtype.Timestamptz
	UpdatedAt              pgtype.Timestamptz
}
